name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Full-year contribution calendar
          filename: metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Achievements Plugin (Compact View)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X   # Show all achievements including locked ones
          plugin_achievements_limit: 0       # 0 = show all
